# Generated by Django 5.1.1 on 2024-09-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('file', models.FileField(upload_to='C:\\Users\\91912\\Desktop\\DOcs\\DBMS_p\\examvault\\media')),
                ('uploaded_by', models.CharField(max_length=100)),
            ],
        ),
    ]
