# Generated by Django 5.1.1 on 2024-09-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='department',
            field=models.CharField(default='', max_length=100),
        ),
    ]
