# Generated by Django 5.1.1 on 2024-09-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_exampaper_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('resume_file', models.FileField(upload_to='C:\\Users\\91912\\Desktop\\DOcs\\DBMS_p\\examvault\\media')),
            ],
        ),
    ]
